### ISSUE TITLE
The description of some message prompt boxes  is not accurate

### ISSUE THREAD

**Issue by Ray-77** [AntShares/AntSharesApp#1]
Sometimes it shows [object Object] or "RangeError", and sometimes it shows nothing.
One more thing, registering assets only consumes 100 ANC now,  the tip on the page of "registering assets"should be changed.

**Comment by Ray-77** [comment]
![3](https://cloud.githubusercontent.com/assets/17636881/18625625/5ea39750-7e82-11e6-9a9a-bffd5a300a01.png)

**Comment by Ray-77** [comment]
![default](https://cloud.githubusercontent.com/assets/17636881/18699643/2cc3aa48-8005-11e6-842e-698098e3e1f5.png)
Click on the button below without filling in the adress, and then  there is no message box appears.

**Comment by Ray-77** [comment]
![default](https://cloud.githubusercontent.com/assets/17636881/19302700/e1384f86-9097-11e6-8a0c-3b7381d51534.png)

**Comment by Ray-77** [comment]
![default](https://cloud.githubusercontent.com/assets/17636881/19305988/1710ba86-90a6-11e6-9057-65cf307c5092.png)

**Comment by Ray-77** [comment]
![11](https://cloud.githubusercontent.com/assets/17636881/19306061/75c00820-90a6-11e6-9543-7dc4a9bc8484.png)

**Comment by PeterLinX** [comment]
fixed. Try again.
