### ISSUE TITLE
It had no response after clicking the button "create" when the pub-key was wrong during creating multi-sig account.

### ISSUE THREAD

**Issue by Ray-77** [AntShares/AntSharesApp#12]
![default](https://cloud.githubusercontent.com/assets/17636881/19304816/cbd17e16-90a0-11e6-9cc9-7a47a8616e1e.png)

**Comment by PeterLinX** [comment]
bug fixed please try again.

**Comment by Ray-77** [comment]
![default](https://cloud.githubusercontent.com/assets/17636881/19383658/1866bad2-9238-11e6-8a53-e087b547c05e.png)
The prompt message box could be more clearly the later.
