### ISSUE TITLE
The default newly added text box is not empty 

### ISSUE THREAD

**Issue by Ray-77** [AntShares/AntSharesApp#2]
![default](https://cloud.githubusercontent.com/assets/17636881/18624891/7c1f12be-7e7d-11e6-8fae-f368d2cfa333.png)

**Comment by chenzhitong** [comment]
It has been fixed on Sep 26, 2016 
[https://github.com/AntShares/AntSharesApp/tree/4d7a0e755d7d572e2e0752cbdf97d7941278c25f](url)
