### ISSUE TITLE
The pub-key of the issuers can not be displayed completely in "My Asset".

### ISSUE THREAD

**Issue by Ray-77** [AntShares/AntSharesApp#21]
![default](https://cloud.githubusercontent.com/assets/17636881/19717668/54199706-9b94-11e6-87bd-288d13eb8801.png)

**Comment by chenzhitong** [comment]
Fixed in 2016/11/4 https://github.com/AntShares/AntSharesApp/commit/85c367b5c23ac0e6a838820fe4fd333c52474f9b

**Comment by chenzhitong** [comment]
Fixed in 2016/11/3 https://github.com/AntShares/AntSharesApp/commit/85c367b5c23ac0e6a838820fe4fd333c52474f9b

**Comment by chenzhitong** [comment]
Fixed in 2016/11/3 https://github.com/AntShares/AntSharesApp/commit/85c367b5c23ac0e6a838820fe4fd333c52474f9b

**Comment by chenzhitong** [comment]
Fixed in 2016/11/3 https://github.com/AntShares/AntSharesApp/commit/85c367b5c23ac0e6a838820fe4fd333c52474f9b

**Comment by chenzhitong** [comment]
Fixed in 2016/11/3 https://github.com/AntShares/AntSharesApp/commit/85c367b5c23ac0e6a838820fe4fd333c52474f9b
