### ISSUE TITLE
some little problems about the UI in APP

### ISSUE THREAD

**Issue by Ray-77** [AntShares/AntSharesApp#26]
![default](https://cloud.githubusercontent.com/assets/17636881/20613852/ecb12d96-b302-11e6-926b-14368cea799c.png)
In the Firefox browser.

**Comment by Ray-77** [comment]
![default](https://cloud.githubusercontent.com/assets/17636881/20613869/37df45a0-b303-11e6-9a39-0ac8f6df02da.png)
The "sync progress " can not be shown completely when the sync progress is too small.

**Comment by chenzhitong** [comment]
Fixed in 2016/11/25
https://github.com/AntShares/AntSharesApp/commit/049326d0373197632a2b9cde589f46f94da02e67
