### ISSUE TITLE
The text boxes are not empty after the transfer

### ISSUE THREAD

**Issue by Ray-77** [AntShares/AntSharesApp#27]
![default](https://cloud.githubusercontent.com/assets/17636881/20738533/cc5df372-b6ee-11e6-8073-56a874eec1e9.png)

**Comment by chenzhitong** [comment]
Fixed in 2016/11/30 https://github.com/AntShares/AntSharesApp/commit/fee7482570944a561155f5f1806ecc02d0f0f96e
