### ISSUE TITLE
The progress is stopped here when the private key was wrong.

### ISSUE THREAD

**Issue by Ray-77** [AntShares/AntSharesApp#28]
![default](https://cloud.githubusercontent.com/assets/17636881/20781714/045dde82-b7c0-11e6-803d-88f69a2bf4a1.png)

**Comment by chenzhitong** [comment]
Fixed in 2016/12/1 https://github.com/AntShares/AntSharesApp/commit/eb8044cb727064a739d9bfa165df13125a09d130
