### ISSUE TITLE
The page cannot be slipped down , so some buttons can not be clicked sometimes

### ISSUE THREAD

**Issue by Ray-77** [AntShares/AntSharesApp#5]
As shown in the following figure,The button at the bottom can not be clicked.
![2](https://cloud.githubusercontent.com/assets/17636881/18625502/a87d1a8c-7e81-11e6-937c-5752aa0b4f73.png)

**Comment by Ray-77** [comment]
It has been fixed now.

**Comment by chenzhitong** [comment]
It has been fixed on Sep 28, 2016 
[https://github.com/AntShares/AntSharesApp/tree/84f9ebe9b1f6096cc94dfa582334865e56987b55](url)

**Comment by chenzhitong** [comment]
It has been fixed on Sep 28, 2016 
[https://github.com/AntShares/AntSharesApp/tree/84f9ebe9b1f6096cc94dfa582334865e56987b55](url)
